name: '[C#] SecureMemory CI'

on:
  workflow_dispatch:

  push:
    paths:
      - 'csharp/SecureMemory/**'
      - '.github/workflows/csharp-securememory-*'

  pull_request:
    branches:
      - main
    paths:
      - 'csharp/SecureMemory/**'
      - '.github/workflows/csharp-securememory-*'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-csharp-sm-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload-artifact.outputs.artifact_id }}
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Add workspace to safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Cache dotnet packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-securememory-${{ hashFiles('csharp/SecureMemory/**/*.csproj') }}-v2

      - name: Build
        run: |
          cd csharp/SecureMemory
          ./scripts/clean.sh
          ./scripts/build.sh

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: csharp-secure-memory
          path: |
            csharp/SecureMemory/SecureMemory/bin/**
            csharp/SecureMemory/SecureMemory/obj/**
            csharp/SecureMemory/PlatformNative/bin/**
            csharp/SecureMemory/PlatformNative/obj/**
            csharp/SecureMemory/SecureMemory.Tests/bin/**
            csharp/SecureMemory/SecureMemory.Tests/obj/**

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/dotnet/sdk:10.0
      options: --ulimit core=-1 --ulimit memlock=-1:-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Cache dotnet packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-securememory-${{ hashFiles('csharp/SecureMemory/**/*.csproj') }}-v2

      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: csharp-secure-memory
          path: ${{ github.workspace }}/csharp/SecureMemory

      - name: Install libssl-1.1
        run: |
          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          rm libssl1.1_1.1.1f-1ubuntu2_amd64.deb

      - name: Run unit tests
        run: |
          cd csharp/SecureMemory
          ./scripts/test.sh

      - name: Unit test summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.3.0
        with:
          paths: 'csharp/SecureMemory/SecureMemory.Tests/test-result.xml'
        if: always()

  release:
    if: startsWith(github.ref, 'refs/heads/release-')
    needs: test
    permissions:
      contents: write
    name: Release
    uses: ./.github/workflows/csharp-securememory-release.yml
    secrets: inherit
