name: Draft release

on:
  push:
    tags:
      - '*/*/v[01].[0-9]+.[0-9]+'

jobs:
  build:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Format release title
        id: format-release-title
        run: |
          REGEX="refs/tags/(.*)/(.*)/(v.*)"

          if [[ $GITHUB_REF =~ $REGEX ]]
          then
              lang="${BASH_REMATCH[1]}"
              lib="${BASH_REMATCH[2]}"
              ver="${BASH_REMATCH[3]}"

              case $lang in

                  csharp)
                      lang="C#"
                      ;;

                  go)
                      lang="Go"
                      ;;

                  java)
                      lang="Java"
                      ;;
              esac

              case $lib in

                  appencryption)
                      lib="AppEncryption"
                      ;;

                  securememory)
                      lib="SecureMemory"
                      ;;
              esac

              title="[${lang}] ${lib} ${ver}"
              echo "::set-output name=release-title::${title}"
          else
              echo "unrecognized github.ref: ${GITHUB_REF}"
              exit 1
          fi
        shell: bash
      - name: Create release
        uses: ncipollo/release-action@eb05307dcee34deaad054e98128088a30d7980dc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: ${{ steps.format-release-title.outputs.release-title }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
